`1.98` cherries
stackitcloud/gardener pull request #104
Opened 2024-10-08 14:29 UTC by Duciwuci

**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:

**Special notes for your reviewer**:

2024-10-08 15:44 UTC, Duciwuci commented
/retest

2024-10-08 15:51 UTC, Duciwuci commented
Currently https://github.com/stackitcloud/gardener/pull/104/commits/6c1dc976c245f289ebc6c42af244ba891acfea14 causes failing integration tests. Must be fixed before continuoing.

2024-10-09 07:40 UTC, Duciwuci commented on pkg/component/networking/apiserverproxy/apiserver_proxy_test.go
> +		  tunneling_config:
This not to seem correct: https://github.com/stackitcloud/gardener/pull/97/commits/a57ce23b3b16917161593165f55f543fd9beb88f#diff-08f1f63ed2f60c43bf365ed0febad215ee59b84095021725dceb61d95c878469

2024-10-09 12:24 UTC, nschad commented
Please also drop commit: b10499c8c928f7b0f37d729c69b2a493bf35d78a

2024-10-09 12:24 UTC, Duciwuci commented
@nschad done <3

2024-10-09 12:31 UTC, Duciwuci commented
/retest

2024-10-09 13:00 UTC, nschad requested changes
@Duciwuci Please **drop** the commit. Do not revert it!. This will PR will rebase merged, that would show up.

2024-10-09 13:23 UTC, Duciwuci commented
There is no need to wait

2024-10-09 13:45 UTC, Duciwuci commented
/retest

2024-10-09 15:39 UTC, maboehm commented
/lgtm

2024-10-09 15:41 UTC, Duciwuci commented
/approve

2024-10-09 15:41 UTC, merged