1.86 cherries
stackitcloud/gardener pull request #66
Opened 2024-04-30 09:07 UTC by Duciwuci

/kind enhancement

2024-04-30 09:17 UTC, Duciwuci commented
/override pull-gardener-e2e-kind

2024-04-30 11:04 UTC, Duciwuci commented
/test pull-gardener-unit

2024-05-02 07:55 UTC, MichaelEischer commented
/hold The second half of cherry-picked commits from https://github.com/gardener/gardener/compare/v1.85.5...stackitcloud:gardener:ske-v1.85 is missing

2024-05-02 08:06 UTC, Duciwuci commented
/hold cancel

Cherries are now picked

2024-05-02 08:13 UTC, MichaelEischer commented
We should also bump etcd-druid to 0.21.1 . The 1.86.4 includes that version in its imagevector

2024-05-02 08:16 UTC, MichaelEischer commented on cmd/gardenlet/app/app.go
> +func cleanupLegacyLoggingManagedResource(ctx context.Context, seedClient client.Client) error {
This function is no longer used. Please remove it.

2024-05-02 08:30 UTC, MichaelEischer commented
/lgtm

2024-05-02 08:48 UTC, nschad commented
/override pull-gardener-e2e-kind

2024-05-02 08:49 UTC, nschad requested changes

2024-05-02 08:49 UTC, nschad commented on VERSION
Can you order this commit to be last in history?

2024-05-02 08:50 UTC, nschad commented on VERSION
Referring to the 12ac6a384cb5e7a2486cdf99836df1e51de20c41 Commit. Just order it to be HEAD of the current branch.

2024-05-02 09:00 UTC, nschad commented
/override pull-gardener-e2e-kind 
/lgtm

2024-05-02 09:04 UTC, nschad commented
/override pull-gardener-e2e-kind

2024-05-02 09:18 UTC, Duciwuci commented
approve

2024-05-02 09:19 UTC, nschad commented
/approve

2024-05-02 09:21 UTC, merged